sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t 01vadim10/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true 01vadim10/react-test npm test

after_success:
  - docker build -t 01vadim10/multi-client ./client
  - docker build -t 01vadim10/multi-nginx ./nginx
  - docker build -t 01vadim10/multi-server ./server
  - docker build -t 01vadim10/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push 01vadim10/multi-client
  - docker push 01vadim10/multi-nginx
  - docker push 01vadim10/multi-server
  - docker push 01vadim10/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-2-840446354595
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY